# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 10:01
from __future__ import unicode_literals

from django.db import migrations

def remove_existing_security_questions(apps, schema_editor):
    SecurityQuestion = apps.get_model('profiles', 'SecurityQuestion')
    SecurityAnswer = apps.get_model('profiles', 'SecurityAnswer')

    # Delete existing security questions and security answers:
    SecurityAnswer.objects.all().delete()
    SecurityQuestion.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('nurseconnect', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_existing_security_questions),
    ]
