# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True)),
                ('path', models.TextField(null=True)),
                ('referer', models.TextField(null=True)),
                ('investigation_uuid', models.TextField(null=True)),
                ('domain', models.TextField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('method', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('visitor_uuid', models.TextField(null=True)),
                ('user_profile_uuid', models.TextField(null=True)),
                ('visitor_id', models.TextField(null=True)),
            ],
        ),
    ]
