from nurseconnect.admin import ArticlePageModelAdmin, YourWordsModelAdminGroup

from wagtailmodeladmin.options import wagtailmodeladmin_register


wagtailmodeladmin_register(ArticlePageModelAdmin)
wagtailmodeladmin_register(YourWordsModelAdminGroup)
